SELECT * FROM worker;

START TRANSACTION;

DELETE FROM worker WHERE WORKER_ID = 1;

ROLLBACK;
--
SAVEPOINT SP1;

INSERT INTO worker VALUES (9,"Jemish","Sakariya",1000000,"13-06-24 01.00.00","Backend");

ROLLBACK TO SAVEPOINT SP1;

RELEASE SAVEPOINT SP1;

COMMIT;